// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ItBZMk8EUpLM0knaMTad2YJxE8vwss4',
    appId: '1:630392030201:web:651a3740b210b3a4a03328',
    messagingSenderId: '630392030201',
    projectId: 'medilearning-4f539',
    authDomain: 'medilearning-4f539.firebaseapp.com',
    storageBucket: 'medilearning-4f539.appspot.com',
    measurementId: 'G-5L6CGTKTMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_CffkjzqWFhnziD4Q670L6wJy3KP5RY',
    appId: '1:630392030201:android:c574287bce0d21b3a03328',
    messagingSenderId: '630392030201',
    projectId: 'medilearning-4f539',
    storageBucket: 'medilearning-4f539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChCt9RlqsCibD6ziTQbzjs9dk1tIlIGTE',
    appId: '1:630392030201:ios:c28abf8791815af8a03328',
    messagingSenderId: '630392030201',
    projectId: 'medilearning-4f539',
    storageBucket: 'medilearning-4f539.appspot.com',
    iosBundleId: 'com.tgde.medilearnpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChCt9RlqsCibD6ziTQbzjs9dk1tIlIGTE',
    appId: '1:630392030201:ios:c28abf8791815af8a03328',
    messagingSenderId: '630392030201',
    projectId: 'medilearning-4f539',
    storageBucket: 'medilearning-4f539.appspot.com',
    iosBundleId: 'com.tgde.medilearnpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2ItBZMk8EUpLM0knaMTad2YJxE8vwss4',
    appId: '1:630392030201:web:895ee5718f513eb1a03328',
    messagingSenderId: '630392030201',
    projectId: 'medilearning-4f539',
    authDomain: 'medilearning-4f539.firebaseapp.com',
    storageBucket: 'medilearning-4f539.appspot.com',
    measurementId: 'G-P15H365BT6',
  );
}
